name: rstrivia
description: An Oldschool Runescape Trivia game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  path_provider: ^1.6.11
  get_it: ^4.0.4
  font_awesome_flutter: ^8.8.1
  modal_progress_hud: ^0.1.3
  basic_utils: ^1.5.1
  json_annotation: ^3.0.1
  intl: ^0.16.1
  animated_text_kit: ^2.2.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  image_cropper: ^1.3.0
  image_picker: ^0.6.7+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/misc/
    - assets/img/items/
    - assets/data/

  fonts:
    - family: Runescape
      fonts:
        - asset: assets/fonts/Runescape.ttf
