import 'package:rstrivia/domain/loot_table_item.dart';

final String kBeginnerTier = 'beginner';
final String kEasyTier = 'easy';
final String kMediumTier = 'medium';
final String kHardTier = 'hard';
final String kEliteTier = 'elite';
final String kMasterTier = 'master';
final String kSharedTier = 'shared';
final double kTierUnlockedAt = 50.0;

final int kLongPressedOpenAmount = 100;

final int kPriceRewardCasketBeginner = 35000;
final int kPriceRewardCasketEasy = 50000;
final int kPriceRewardCasketMedium = 100000;
final int kPriceRewardCasketHard = 250000;
final int kPriceRewardCasketElite = 100000;
final int kPriceRewardCasketMaster = 150000;

final List<int> kLongPressedOpenAmounts = [1, 5, 10, 25, 50, 100];
final List<int> kLongPressedOpenAmountPrices = [
  0,
  25000,
  50000,
  150000,
  300000,
  500000
];

final List<int> kRewardCasketMultipliers = [1, 2, 3, 4, 5];
final List<int> kRewardCasketMultiplierPrices = [
  0,
  250000,
  500000,
  750000,
  1000000
];

final List<LootTableItem> kBeginnerRewardUniqueTableItems = [
  LootTableItem(name: 'Mole slippers', weight: 1),
  LootTableItem(name: 'Frog slippers', weight: 1),
  LootTableItem(name: 'Bear feet', weight: 1),
  LootTableItem(name: 'Demon feet', weight: 1),
  LootTableItem(name: 'Jester cape', weight: 1),
  LootTableItem(name: 'Shoulder parrot', weight: 1),
  LootTableItem(name: 'Monk\'s robe top (t)', weight: 1),
  LootTableItem(name: 'Monk\'s robe (t)', weight: 1),
  LootTableItem(name: 'Amulet of defence (t)', weight: 1),
  LootTableItem(name: 'Sandwich lady hat', weight: 1),
  LootTableItem(name: 'Sandwich lady top', weight: 1),
  LootTableItem(name: 'Sandwich lady bottom', weight: 1),
  LootTableItem(name: 'Rune scimitar ornament kit (guthix)', weight: 1),
  LootTableItem(name: 'Rune scimitar ornament kit (saradomin)', weight: 1),
  LootTableItem(name: 'Rune scimitar ornament kit (zamorak)', weight: 1)
];

final List<LootTableItem> kBeginnerRewardBlackTableItems = [
  LootTableItem(name: 'Black 2h sword', weight: 1),
  LootTableItem(name: 'Black axe', weight: 1),
  LootTableItem(name: 'Black battleaxe', weight: 1),
  LootTableItem(name: 'Black chainbody', weight: 1),
  LootTableItem(name: 'Black dagger', weight: 1),
  LootTableItem(name: 'Black full helm', weight: 1),
  LootTableItem(name: 'Black kiteshield', weight: 1),
  LootTableItem(name: 'Black longsword', weight: 1),
  LootTableItem(name: 'Black mace', weight: 1),
  LootTableItem(name: 'Black med helm', weight: 1),
  LootTableItem(name: 'Black pickaxe', weight: 1),
  LootTableItem(name: 'Black platebody', weight: 1),
  LootTableItem(name: 'Black plateskirt', weight: 1),
  LootTableItem(name: 'Black platelegs', weight: 1),
  LootTableItem(name: 'Black sq shield', weight: 1),
  LootTableItem(name: 'Black scimitar', weight: 1),
  LootTableItem(name: 'Black sword', weight: 1),
  LootTableItem(name: 'Black warhammer', weight: 1)
];

final List<LootTableItem> kBeginnerRewardCommonTableItems = [
  LootTableItem(name: 'Shortbow', weight: 1),
  LootTableItem(name: 'Longbow', weight: 1),
  LootTableItem(name: 'Oak shortbow', weight: 1),
  LootTableItem(name: 'Oak longbow', weight: 1),
  LootTableItem(name: 'Iron pickaxe', weight: 1),
  LootTableItem(name: 'Staff of air', weight: 1),
  LootTableItem(name: 'Staff of water', weight: 1),
  LootTableItem(name: 'Staff of earth', weight: 1),
  LootTableItem(name: 'Staff of fire', weight: 1),
  LootTableItem(name: 'Steel full helm', weight: 1),
  LootTableItem(name: 'Steel platebody', weight: 1),
  LootTableItem(name: 'Steel platelegs', weight: 1),
  LootTableItem(name: 'Steel plateskirt', weight: 1),
  LootTableItem(name: 'Steel longsword', weight: 1),
  LootTableItem(name: 'Steel dagger', weight: 1),
  LootTableItem(name: 'Steel axe', weight: 1),
  LootTableItem(name: 'Steel battleaxe', weight: 1),
  LootTableItem(name: 'Leather cowl', weight: 1),
  LootTableItem(name: 'Leather body', weight: 1),
  LootTableItem(name: 'Leather chaps', weight: 1),
  LootTableItem(name: 'Leather vambraces', weight: 1),
  LootTableItem(name: 'Hardleather body', weight: 1),
  LootTableItem(name: 'Blue wizard hat', weight: 1),
  LootTableItem(name: 'Blue wizard robe', weight: 1),
  LootTableItem(name: 'Wizard hat', weight: 1),
  LootTableItem(name: 'Black robe', weight: 1),
  LootTableItem.quantity(
      name: 'Air rune', weight: 1, quantityMin: 15, quantityMax: 35),
  LootTableItem.quantity(
      name: 'Mind rune', weight: 1, quantityMin: 15, quantityMax: 35),
  LootTableItem.quantity(
      name: 'Water rune', weight: 1, quantityMin: 15, quantityMax: 35),
  LootTableItem.quantity(
      name: 'Earth rune', weight: 1, quantityMin: 15, quantityMax: 35),
  LootTableItem.quantity(
      name: 'Fire rune', weight: 1, quantityMin: 15, quantityMax: 35),
  LootTableItem.quantity(
      name: 'Body rune', weight: 1, quantityMin: 15, quantityMax: 35),
  LootTableItem.quantity(
      name: 'Chaos rune', weight: 1, quantityMin: 2, quantityMax: 7),
  LootTableItem.quantity(
      name: 'Nature rune', weight: 1, quantityMin: 2, quantityMax: 9),
  LootTableItem.quantity(
      name: 'Law rune', weight: 1, quantityMin: 2, quantityMax: 7),
  LootTableItem.quantity(
      name: 'Bronze arrow', weight: 1, quantityMin: 10, quantityMax: 25),
  LootTableItem.quantity(
      name: 'Iron arrow', weight: 1, quantityMin: 7, quantityMax: 25),
  LootTableItem.quantity(
      name: 'Shrimps', weight: 1, quantityMin: 5, quantityMax: 14),
  LootTableItem.quantity(
      name: 'Sardine', weight: 1, quantityMin: 5, quantityMax: 17),
  LootTableItem.quantity(
      name: 'Herring', weight: 1, quantityMin: 5, quantityMax: 9)
];

final List<LootTableItem> kEasyRewardUniqueTableItems = [
  LootTableItem(name: 'Amulet of magic (t)', weight: 8),
  LootTableItem(name: 'Wooden shield (g)', weight: 8),
  LootTableItem(name: 'Black full helm (t)', weight: 8),
  LootTableItem(name: 'Black platebody (t)', weight: 8),
  LootTableItem(name: 'Black platelegs (t)', weight: 8),
  LootTableItem(name: 'Black plateskirt (t)', weight: 8),
  LootTableItem(name: 'Black kiteshield (t)', weight: 8),
  LootTableItem(name: 'Black full helm (g)', weight: 8),
  LootTableItem(name: 'Black platebody (g)', weight: 8),
  LootTableItem(name: 'Black platelegs (g)', weight: 8),
  LootTableItem(name: 'Black plateskirt (g)', weight: 8),
  LootTableItem(name: 'Black kiteshield (g)', weight: 8),
  LootTableItem(name: 'Black shield (h1)', weight: 8),
  LootTableItem(name: 'Black shield (h2)', weight: 8),
  LootTableItem(name: 'Black shield (h3)', weight: 8),
  LootTableItem(name: 'Black shield (h4)', weight: 8),
  LootTableItem(name: 'Black shield (h5)', weight: 8),
  LootTableItem(name: 'Black helm (h1)', weight: 8),
  LootTableItem(name: 'Black helm (h2)', weight: 8),
  LootTableItem(name: 'Black helm (h3)', weight: 8),
  LootTableItem(name: 'Black helm (h4)', weight: 8),
  LootTableItem(name: 'Black helm (h5)', weight: 8),
  LootTableItem(name: 'Black platebody (h1)', weight: 8),
  LootTableItem(name: 'Black platebody (h2)', weight: 8),
  LootTableItem(name: 'Black platebody (h3)', weight: 8),
  LootTableItem(name: 'Black platebody (h4)', weight: 8),
  LootTableItem(name: 'Black platebody (h5)', weight: 8),
  LootTableItem(name: 'Steel full helm (t)', weight: 8),
  LootTableItem(name: 'Steel platebody (t)', weight: 8),
  LootTableItem(name: 'Steel platelegs (t)', weight: 8),
  LootTableItem(name: 'Steel plateskirt (t)', weight: 8),
  LootTableItem(name: 'Steel kiteshield (t)', weight: 8),
  LootTableItem(name: 'Steel full helm (g)', weight: 8),
  LootTableItem(name: 'Steel platebody (g)', weight: 8),
  LootTableItem(name: 'Steel platelegs (g)', weight: 8),
  LootTableItem(name: 'Steel plateskirt (g)', weight: 8),
  LootTableItem(name: 'Steel kiteshield (g)', weight: 8),
  LootTableItem(name: 'Iron full helm (t)', weight: 8),
  LootTableItem(name: 'Iron platebody (t)', weight: 8),
  LootTableItem(name: 'Iron platelegs (t)', weight: 8),
  LootTableItem(name: 'Iron plateskirt (t)', weight: 8),
  LootTableItem(name: 'Iron kiteshield (t)', weight: 8),
  LootTableItem(name: 'Iron full helm (g)', weight: 8),
  LootTableItem(name: 'Iron platebody (g)', weight: 8),
  LootTableItem(name: 'Iron platelegs (g)', weight: 8),
  LootTableItem(name: 'Iron plateskirt (g)', weight: 8),
  LootTableItem(name: 'Iron kiteshield (g)', weight: 8),
  LootTableItem(name: 'Bronze full helm (t)', weight: 8),
  LootTableItem(name: 'Bronze platebody (t)', weight: 8),
  LootTableItem(name: 'Bronze platelegs (t)', weight: 8),
  LootTableItem(name: 'Bronze plateskirt (t)', weight: 8),
  LootTableItem(name: 'Bronze kiteshield (t)', weight: 8),
  LootTableItem(name: 'Bronze full helm (g)', weight: 8),
  LootTableItem(name: 'Bronze platebody (g)', weight: 8),
  LootTableItem(name: 'Bronze platelegs (g)', weight: 8),
  LootTableItem(name: 'Bronze plateskirt (g)', weight: 8),
  LootTableItem(name: 'Bronze kiteshield (g)', weight: 8),
  LootTableItem(name: 'Studded body (g)', weight: 8),
  LootTableItem(name: 'Studded chaps (g)', weight: 8),
  LootTableItem(name: 'Studded body (t)', weight: 8),
  LootTableItem(name: 'Studded chaps (t)', weight: 8),
  LootTableItem(name: 'Leather body (g)', weight: 8),
  LootTableItem(name: 'Leather chaps (g)', weight: 8),
  LootTableItem(name: 'Blue wizard hat (g)', weight: 8),
  LootTableItem(name: 'Blue wizard robe (g)', weight: 8),
  LootTableItem(name: 'Blue skirt (g)', weight: 8),
  LootTableItem(name: 'Blue wizard hat (t)', weight: 8),
  LootTableItem(name: 'Blue wizard robe (t)', weight: 8),
  LootTableItem(name: 'Blue skirt (t)', weight: 8),
  LootTableItem(name: 'Black wizard hat (g)', weight: 8),
  LootTableItem(name: 'Black wizard robe (g)', weight: 8),
  LootTableItem(name: 'Black skirt (g)', weight: 8),
  LootTableItem(name: 'Black wizard hat (t)', weight: 8),
  LootTableItem(name: 'Black wizard robe (t)', weight: 8),
  LootTableItem(name: 'Black skirt (t)', weight: 8),
  LootTableItem(name: 'Saradomin robe top', weight: 8),
  LootTableItem(name: 'Saradomin robe legs', weight: 8),
  LootTableItem(name: 'Guthix robe top', weight: 8),
  LootTableItem(name: 'Guthix robe legs', weight: 8),
  LootTableItem(name: 'Zamorak robe top', weight: 8),
  LootTableItem(name: 'Zamorak robe legs', weight: 8),
  LootTableItem(name: 'Ancient robe top', weight: 8),
  LootTableItem(name: 'Ancient robe legs', weight: 8),
  LootTableItem(name: 'Armadyl robe top', weight: 8),
  LootTableItem(name: 'Armadyl robe legs', weight: 8),
  LootTableItem(name: 'Bandos robe top', weight: 8),
  LootTableItem(name: 'Bandos robe legs', weight: 8),
  LootTableItem(name: 'Bob\'s red shirt', weight: 8),
  LootTableItem(name: 'Bob\'s green shirt', weight: 8),
  LootTableItem(name: 'Bob\'s blue shirt', weight: 8),
  LootTableItem(name: 'Bob\'s black shirt', weight: 8),
  LootTableItem(name: 'Bob\'s purple shirt', weight: 8),
  LootTableItem(name: 'Highwayman mask', weight: 8),
  LootTableItem(name: 'Blue beret', weight: 8),
  LootTableItem(name: 'Black beret', weight: 8),
  LootTableItem(name: 'Red beret', weight: 8),
  LootTableItem(name: 'White beret', weight: 8),
  LootTableItem(name: 'A powdered wig', weight: 8),
  LootTableItem(name: 'Beanie', weight: 8),
  LootTableItem(name: 'Imp mask', weight: 8),
  LootTableItem(name: 'Goblin mask', weight: 8),
  LootTableItem(name: 'Sleeping cap', weight: 8),
  LootTableItem(name: 'Flared trousers', weight: 8),
  LootTableItem(name: 'Pantaloons', weight: 8),
  LootTableItem(name: 'Black cane', weight: 8),
  LootTableItem(name: 'Staff of bob the cat', weight: 8),
  LootTableItem(name: 'Amulet of power (t)', weight: 8),
  LootTableItem(name: 'Ham joint', weight: 8),
  LootTableItem(name: 'Rain bow', weight: 8),
  LootTableItem(name: 'Golden chef\'s hat', weight: 4),
  LootTableItem(name: 'Golden apron', weight: 4),
  LootTableItem(name: 'Red elegant shirt', weight: 4),
  LootTableItem(name: 'Red elegant blouse', weight: 4),
  LootTableItem(name: 'Red elegant legs', weight: 4),
  LootTableItem(name: 'Red elegant skirt', weight: 4),
  LootTableItem(name: 'Green elegant shirt', weight: 4),
  LootTableItem(name: 'Green elegant blouse', weight: 4),
  LootTableItem(name: 'Green elegant legs', weight: 4),
  LootTableItem(name: 'Green elegant skirt', weight: 4),
  LootTableItem(name: 'Blue elegant shirt', weight: 4),
  LootTableItem(name: 'Blue elegant blouse', weight: 4),
  LootTableItem(name: 'Blue elegant legs', weight: 4),
  LootTableItem(name: 'Blue elegant skirt', weight: 4),
  LootTableItem(name: 'Team cape zero', weight: 2),
  LootTableItem(name: 'Team cape i', weight: 2),
  LootTableItem(name: 'Team cape x', weight: 2),
  LootTableItem(name: 'Cape of skulls', weight: 2),
  LootTableItem(name: 'Monk\'s robe top (g)', weight: 1),
  LootTableItem(name: 'Monk\'s robe (g)', weight: 1),
];

final List<LootTableItem> kEasyRewardCommonTableItems = [
  LootTableItem(name: 'Black full helm', weight: 9),
  LootTableItem(name: 'Black platebody', weight: 9),
  LootTableItem(name: 'Black platelegs', weight: 9),
  LootTableItem(name: 'Black longsword', weight: 9),
  LootTableItem(name: 'Black battleaxe', weight: 9),
  LootTableItem(name: 'Black axe', weight: 9),
  LootTableItem(name: 'Black dagger', weight: 9),
  LootTableItem(name: 'Black pickaxe', weight: 9),
  LootTableItem(name: 'Steel pickaxe', weight: 9),
  LootTableItem(name: 'Coif', weight: 9),
  LootTableItem(name: 'Studded body', weight: 9),
  LootTableItem(name: 'Studded chaps', weight: 9),
  LootTableItem(name: 'Willow shortbow', weight: 9),
  LootTableItem(name: 'Staff of air', weight: 9),
  LootTableItem(name: 'Willow longbow', weight: 9),
  LootTableItem(name: 'Amulet of magic', weight: 9),
  LootTableItem(name: 'Willow comp bow', weight: 1),
  LootTableItem.quantity(
      name: 'Air rune', weight: 9, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Mind rune', weight: 9, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Water rune', weight: 9, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Earth rune', weight: 9, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Fire rune', weight: 9, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Body rune', weight: 9, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Chaos rune', weight: 9, quantityMin: 5, quantityMax: 10),
  LootTableItem.quantity(
      name: 'Nature rune', weight: 9, quantityMin: 5, quantityMax: 10),
  LootTableItem.quantity(
      name: 'Law rune', weight: 9, quantityMin: 5, quantityMax: 10),
  LootTableItem.quantity(
      name: 'Trout', weight: 9, quantityMin: 6, quantityMax: 10),
  LootTableItem.quantity(
      name: 'Salmon', weight: 9, quantityMin: 6, quantityMax: 10)
];

final List<LootTableItem> kMediumRewardUniqueTableItems = [
  LootTableItem(name: 'Ranger boots', weight: 2),
  LootTableItem(name: 'Wizard boots', weight: 2),
  LootTableItem(name: 'Holy sandals', weight: 2),
  LootTableItem(name: 'Spiked manacles', weight: 2),
  LootTableItem(name: 'Climbing boots (g)', weight: 2),
  LootTableItem(name: 'Adamant full helm (t)', weight: 2),
  LootTableItem(name: 'Adamant platebody (t)', weight: 2),
  LootTableItem(name: 'Adamant platelegs (t)', weight: 2),
  LootTableItem(name: 'Adamant plateskirt (t)', weight: 2),
  LootTableItem(name: 'Adamant kiteshield (t)', weight: 2),
  LootTableItem(name: 'Adamant full helm (g)', weight: 2),
  LootTableItem(name: 'Adamant platebody (g)', weight: 2),
  LootTableItem(name: 'Adamant platelegs (g)', weight: 2),
  LootTableItem(name: 'Adamant plateskirt (g)', weight: 2),
  LootTableItem(name: 'Adamant kiteshield (g)', weight: 2),
  LootTableItem(name: 'Adamant shield (h1)', weight: 2),
  LootTableItem(name: 'Adamant shield (h2)', weight: 2),
  LootTableItem(name: 'Adamant shield (h3)', weight: 2),
  LootTableItem(name: 'Adamant shield (h4)', weight: 2),
  LootTableItem(name: 'Adamant shield (h5)', weight: 2),
  LootTableItem(name: 'Adamant helm (h1)', weight: 2),
  LootTableItem(name: 'Adamant helm (h2)', weight: 2),
  LootTableItem(name: 'Adamant helm (h3)', weight: 2),
  LootTableItem(name: 'Adamant helm (h4)', weight: 2),
  LootTableItem(name: 'Adamant helm (h5)', weight: 2),
  LootTableItem(name: 'Adamant platebody (h1)', weight: 2),
  LootTableItem(name: 'Adamant platebody (h2)', weight: 2),
  LootTableItem(name: 'Adamant platebody (h3)', weight: 2),
  LootTableItem(name: 'Adamant platebody (h4)', weight: 2),
  LootTableItem(name: 'Adamant platebody (h5)', weight: 2),
  LootTableItem(name: 'Mithril full helm (g)', weight: 2),
  LootTableItem(name: 'Mithril platebody (g)', weight: 2),
  LootTableItem(name: 'Mithril platelegs (g)', weight: 2),
  LootTableItem(name: 'Mithril plateskirt (g)', weight: 2),
  LootTableItem(name: 'Mithril kiteshield (g)', weight: 2),
  LootTableItem(name: 'Mithril full helm (t)', weight: 2),
  LootTableItem(name: 'Mithril platebody (t)', weight: 2),
  LootTableItem(name: 'Mithril platelegs (t)', weight: 2),
  LootTableItem(name: 'Mithril plateskirt (t)', weight: 2),
  LootTableItem(name: 'Mithril kiteshield (t)', weight: 2),
  LootTableItem(name: 'Green d\'hide body (g)', weight: 2),
  LootTableItem(name: 'Green d\'hide chaps (g)', weight: 2),
  LootTableItem(name: 'Green d\'hide body (t)', weight: 2),
  LootTableItem(name: 'Green d\'hide chaps (t)', weight: 2),
  LootTableItem(name: 'Saradomin mitre', weight: 2),
  LootTableItem(name: 'Saradomin cloak', weight: 2),
  LootTableItem(name: 'Guthix mitre', weight: 2),
  LootTableItem(name: 'Guthix cloak', weight: 2),
  LootTableItem(name: 'Zamorak mitre', weight: 2),
  LootTableItem(name: 'Zamorak cloak', weight: 2),
  LootTableItem(name: 'Ancient mitre', weight: 2),
  LootTableItem(name: 'Ancient cloak', weight: 2),
  LootTableItem(name: 'Ancient stole', weight: 2),
  LootTableItem(name: 'Ancient crozier', weight: 2),
  LootTableItem(name: 'Armadyl mitre', weight: 2),
  LootTableItem(name: 'Armadyl cloak', weight: 2),
  LootTableItem(name: 'Armadyl stole', weight: 2),
  LootTableItem(name: 'Armadyl crozier', weight: 2),
  LootTableItem(name: 'Bandos mitre', weight: 2),
  LootTableItem(name: 'Bandos cloak', weight: 2),
  LootTableItem(name: 'Bandos stole', weight: 2),
  LootTableItem(name: 'Bandos crozier', weight: 2),
  LootTableItem(name: 'Red boater', weight: 2),
  LootTableItem(name: 'Green boater', weight: 2),
  LootTableItem(name: 'Orange boater', weight: 2),
  LootTableItem(name: 'Black boater', weight: 2),
  LootTableItem(name: 'Blue boater', weight: 2),
  LootTableItem(name: 'Pink boater', weight: 2),
  LootTableItem(name: 'Purple boater', weight: 2),
  LootTableItem(name: 'White boater', weight: 2),
  LootTableItem(name: 'Red headband', weight: 2),
  LootTableItem(name: 'Black headband', weight: 2),
  LootTableItem(name: 'Brown headband', weight: 2),
  LootTableItem(name: 'White headband', weight: 2),
  LootTableItem(name: 'Blue headband', weight: 2),
  LootTableItem(name: 'Gold headband', weight: 2),
  LootTableItem(name: 'Pink headband', weight: 2),
  LootTableItem(name: 'Green headband', weight: 2),
  LootTableItem(name: 'Adamant cane', weight: 2),
  LootTableItem(name: 'Cat mask', weight: 2),
  LootTableItem(name: 'Penguin mask', weight: 2),
  LootTableItem(name: 'Leprechaun hat', weight: 2),
  LootTableItem(name: 'Crier hat', weight: 2),
  LootTableItem(name: 'Crier coat', weight: 2),
  LootTableItem(name: 'Crier bell', weight: 2),
  LootTableItem(name: 'Arceuus banner', weight: 2),
  LootTableItem(name: 'Piscarilius banner', weight: 2),
  LootTableItem(name: 'Hosidius banner', weight: 2),
  LootTableItem(name: 'Shayzien banner', weight: 2),
  LootTableItem(name: 'Lovakengj banner', weight: 2),
  LootTableItem(name: 'Cabbage round shield', weight: 2),
  LootTableItem(name: 'Wolf mask', weight: 2),
  LootTableItem(name: 'Wolf cloak', weight: 2),
  LootTableItem(name: 'Black leprechaun hat', weight: 2),
  LootTableItem(name: 'Black unicorn mask', weight: 1),
  LootTableItem(name: 'White unicorn mask', weight: 1),
  LootTableItem(name: 'Purple elegant shirt', weight: 1),
  LootTableItem(name: 'Purple elegant blouse', weight: 1),
  LootTableItem(name: 'Purple elegant legs', weight: 1),
  LootTableItem(name: 'Purple elegant skirt', weight: 1),
  LootTableItem(name: 'Black elegant shirt', weight: 1),
  LootTableItem(name: 'White elegant blouse', weight: 1),
  LootTableItem(name: 'Black elegant legs', weight: 1),
  LootTableItem(name: 'White elegant skirt', weight: 1),
  LootTableItem(name: 'Pink elegant shirt', weight: 1),
  LootTableItem(name: 'Pink elegant blouse', weight: 1),
  LootTableItem(name: 'Pink elegant legs', weight: 1),
  LootTableItem(name: 'Pink elegant skirt', weight: 1),
  LootTableItem(name: 'Gold elegant shirt', weight: 1),
  LootTableItem(name: 'Gold elegant blouse', weight: 1),
  LootTableItem(name: 'Gold elegant legs', weight: 1),
  LootTableItem(name: 'Gold elegant skirt', weight: 1),
];

final List<LootTableItem> kMediumRewardCommonTableItems = [
  LootTableItem(name: 'Adamant full helm', weight: 10),
  LootTableItem(name: 'Adamant platebody', weight: 10),
  LootTableItem(name: 'Adamant platelegs', weight: 10),
  LootTableItem(name: 'Adamant longsword', weight: 10),
  LootTableItem(name: 'Adamant dagger', weight: 10),
  LootTableItem(name: 'Adamant battleaxe', weight: 10),
  LootTableItem(name: 'Adamant axe', weight: 10),
  LootTableItem(name: 'Adamant pickaxe', weight: 10),
  LootTableItem(name: 'Green d\'hide body', weight: 10),
  LootTableItem(name: 'Green d\'hide chaps', weight: 10),
  LootTableItem(name: 'Yew shortbow', weight: 10),
  LootTableItem(name: 'Fire battlestaff', weight: 10),
  LootTableItem(name: 'Yew longbow', weight: 10),
  LootTableItem(name: 'Amulet of power', weight: 10),
  LootTableItem(name: 'Yew comp bow', weight: 1),
  LootTableItem(name: 'Strength amulet (t)', weight: 1),
  LootTableItem.quantity(
      name: 'Air rune', weight: 10, quantityMin: 50, quantityMax: 100),
  LootTableItem.quantity(
      name: 'Mind rune', weight: 10, quantityMin: 50, quantityMax: 100),
  LootTableItem.quantity(
      name: 'Water rune', weight: 10, quantityMin: 50, quantityMax: 100),
  LootTableItem.quantity(
      name: 'Earth rune', weight: 10, quantityMin: 50, quantityMax: 100),
  LootTableItem.quantity(
      name: 'Fire rune', weight: 10, quantityMin: 50, quantityMax: 100),
  LootTableItem.quantity(
      name: 'Chaos rune', weight: 10, quantityMin: 10, quantityMax: 20),
  LootTableItem.quantity(
      name: 'Nature rune', weight: 10, quantityMin: 10, quantityMax: 20),
  LootTableItem.quantity(
      name: 'Law rune', weight: 10, quantityMin: 10, quantityMax: 20),
  LootTableItem.quantity(
      name: 'Death rune', weight: 10, quantityMin: 10, quantityMax: 20),
  LootTableItem.quantity(
      name: 'Lobster', weight: 10, quantityMin: 8, quantityMax: 12),
  LootTableItem.quantity(
      name: 'Swordfish', weight: 10, quantityMin: 8, quantityMax: 12),
];

final List<LootTableItem> kHardRewardMegaRareTableItems = [
  LootTableItem.quantity(
      name: 'Super energy(4)', weight: 13, quantityMin: 15, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Super restore(4)', weight: 13, quantityMin: 15, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Antifire potion(4)', weight: 13, quantityMin: 15, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Super combat potion(4)',
      weight: 13,
      quantityMin: 15,
      quantityMax: 15),
  LootTableItem(name: 'Gilded full helm', weight: 6),
  LootTableItem(name: 'Gilded platebody', weight: 6),
  LootTableItem(name: 'Gilded platelegs', weight: 6),
  LootTableItem(name: 'Gilded plateskirt', weight: 6),
  LootTableItem(name: 'Gilded kiteshield', weight: 6),
  LootTableItem(name: 'Gilded med helm', weight: 6),
  LootTableItem(name: 'Gilded chainbody', weight: 6),
  LootTableItem(name: 'Gilded sq shield', weight: 6),
  LootTableItem(name: 'Gilded 2h sword', weight: 6),
  LootTableItem(name: 'Gilded spear', weight: 6),
  LootTableItem(name: 'Gilded hasta', weight: 6),
  LootTableItem(name: '3rd age full helmet', weight: 1),
  LootTableItem(name: '3rd age platebody', weight: 1),
  LootTableItem(name: '3rd age platelegs', weight: 1),
  LootTableItem(name: '3rd age plateskirt', weight: 1),
  LootTableItem(name: '3rd age kiteshield', weight: 1),
  LootTableItem(name: '3rd age range coif', weight: 1),
  LootTableItem(name: '3rd age range top', weight: 1),
  LootTableItem(name: '3rd age range legs', weight: 1),
  LootTableItem(name: '3rd age vambraces', weight: 1),
  LootTableItem(name: '3rd age mage hat', weight: 1),
  LootTableItem(name: '3rd age robe top', weight: 1),
  LootTableItem(name: '3rd age robe', weight: 1),
  LootTableItem(name: '3rd age amulet', weight: 1),
];

final List<LootTableItem> kHardRewardUniqueTableItems = [
  LootTableItem(name: 'Robin hood hat', weight: 6),
  LootTableItem(name: 'Enchanted hat', weight: 6),
  LootTableItem(name: 'Enchanted top', weight: 6),
  LootTableItem(name: 'Enchanted robe', weight: 6),
  LootTableItem(name: 'Rune full helm (t)', weight: 6),
  LootTableItem(name: 'Rune platebody (t)', weight: 6),
  LootTableItem(name: 'Rune platelegs (t)', weight: 6),
  LootTableItem(name: 'Rune plateskirt (t)', weight: 6),
  LootTableItem(name: 'Rune kiteshield (t)', weight: 6),
  LootTableItem(name: 'Rune full helm (g)', weight: 6),
  LootTableItem(name: 'Rune platebody (g)', weight: 6),
  LootTableItem(name: 'Rune platelegs (g)', weight: 6),
  LootTableItem(name: 'Rune plateskirt (g)', weight: 6),
  LootTableItem(name: 'Rune kiteshield (g)', weight: 6),
  LootTableItem(name: 'Rune helm (h1)', weight: 6),
  LootTableItem(name: 'Rune helm (h2)', weight: 6),
  LootTableItem(name: 'Rune helm (h3)', weight: 6),
  LootTableItem(name: 'Rune helm (h4)', weight: 6),
  LootTableItem(name: 'Rune helm (h5)', weight: 6),
  LootTableItem(name: 'Rune platebody (h1)', weight: 1),
  LootTableItem(name: 'Rune platebody (h2)', weight: 1),
  LootTableItem(name: 'Rune platebody (h3)', weight: 1),
  LootTableItem(name: 'Rune platebody (h4)', weight: 1),
  LootTableItem(name: 'Rune platebody (h5)', weight: 1),
  LootTableItem(name: 'Rune shield (h1)', weight: 6),
  LootTableItem(name: 'Rune shield (h2)', weight: 6),
  LootTableItem(name: 'Rune shield (h3)', weight: 6),
  LootTableItem(name: 'Rune shield (h4)', weight: 6),
  LootTableItem(name: 'Rune shield (h5)', weight: 6),
  LootTableItem(name: 'Zamorak full helm', weight: 6),
  LootTableItem(name: 'Zamorak platebody', weight: 6),
  LootTableItem(name: 'Zamorak platelegs', weight: 6),
  LootTableItem(name: 'Zamorak plateskirt', weight: 6),
  LootTableItem(name: 'Zamorak kiteshield', weight: 6),
  LootTableItem(name: 'Guthix full helm', weight: 6),
  LootTableItem(name: 'Guthix platebody', weight: 6),
  LootTableItem(name: 'Guthix platelegs', weight: 6),
  LootTableItem(name: 'Guthix plateskirt', weight: 6),
  LootTableItem(name: 'Guthix kiteshield', weight: 6),
  LootTableItem(name: 'Saradomin full helm', weight: 6),
  LootTableItem(name: 'Saradomin platebody', weight: 6),
  LootTableItem(name: 'Saradomin platelegs', weight: 6),
  LootTableItem(name: 'Saradomin plateskirt', weight: 6),
  LootTableItem(name: 'Saradomin kiteshield', weight: 6),
  LootTableItem(name: 'Ancient full helm', weight: 6),
  LootTableItem(name: 'Ancient platebody', weight: 6),
  LootTableItem(name: 'Ancient platelegs', weight: 6),
  LootTableItem(name: 'Ancient plateskirt', weight: 6),
  LootTableItem(name: 'Ancient kiteshield', weight: 6),
  LootTableItem(name: 'Armadyl full helm', weight: 6),
  LootTableItem(name: 'Armadyl platebody', weight: 6),
  LootTableItem(name: 'Armadyl platelegs', weight: 6),
  LootTableItem(name: 'Armadyl plateskirt', weight: 6),
  LootTableItem(name: 'Armadyl kiteshield', weight: 6),
  LootTableItem(name: 'Bandos full helm', weight: 6),
  LootTableItem(name: 'Bandos platebody', weight: 6),
  LootTableItem(name: 'Bandos platelegs', weight: 6),
  LootTableItem(name: 'Bandos plateskirt', weight: 6),
  LootTableItem(name: 'Bandos kiteshield', weight: 6),
  LootTableItem(name: 'Red d\'hide body (g)', weight: 6),
  LootTableItem(name: 'Red d\'hide chaps (g)', weight: 6),
  LootTableItem(name: 'Red d\'hide body (t)', weight: 6),
  LootTableItem(name: 'Red d\'hide chaps (t)', weight: 6),
  LootTableItem(name: 'Blue d\'hide body (g)', weight: 6),
  LootTableItem(name: 'Blue d\'hide chaps (g)', weight: 6),
  LootTableItem(name: 'Blue d\'hide body (t)', weight: 6),
  LootTableItem(name: 'Blue d\'hide chaps (t)', weight: 6),
  LootTableItem(name: 'Saradomin coif', weight: 6),
  LootTableItem(name: 'Saradomin d\'hide body', weight: 6),
  LootTableItem(name: 'Saradomin chaps', weight: 6),
  LootTableItem(name: 'Saradomin bracers', weight: 6),
  LootTableItem(name: 'Saradomin d\'hide boots', weight: 6),
  LootTableItem(name: 'Saradomin d\'hide shield', weight: 1),
  LootTableItem(name: 'Guthix coif', weight: 6),
  LootTableItem(name: 'Guthix d\'hide body', weight: 6),
  LootTableItem(name: 'Guthix chaps', weight: 6),
  LootTableItem(name: 'Guthix bracers', weight: 6),
  LootTableItem(name: 'Guthix d\'hide boots', weight: 6),
  LootTableItem(name: 'Guthix d\'hide shield', weight: 1),
  LootTableItem(name: 'Zamorak coif', weight: 6),
  LootTableItem(name: 'Zamorak d\'hide body', weight: 6),
  LootTableItem(name: 'Zamorak chaps', weight: 6),
  LootTableItem(name: 'Zamorak bracers', weight: 6),
  LootTableItem(name: 'Zamorak d\'hide boots', weight: 6),
  LootTableItem(name: 'Zamorak d\'hide shield', weight: 1),
  LootTableItem(name: 'Bandos coif', weight: 6),
  LootTableItem(name: 'Bandos d\'hide body', weight: 6),
  LootTableItem(name: 'Bandos chaps', weight: 6),
  LootTableItem(name: 'Bandos bracers', weight: 6),
  LootTableItem(name: 'Bandos d\'hide boots', weight: 6),
  LootTableItem(name: 'Bandos d\'hide shield', weight: 1),
  LootTableItem(name: 'Armadyl coif', weight: 6),
  LootTableItem(name: 'Armadyl d\'hide body', weight: 6),
  LootTableItem(name: 'Armadyl chaps', weight: 6),
  LootTableItem(name: 'Armadyl bracers', weight: 6),
  LootTableItem(name: 'Armadyl d\'hide boots', weight: 6),
  LootTableItem(name: 'Armadyl d\'hide shield', weight: 1),
  LootTableItem(name: 'Ancient coif', weight: 6),
  LootTableItem(name: 'Ancient d\'hide body', weight: 6),
  LootTableItem(name: 'Ancient chaps', weight: 6),
  LootTableItem(name: 'Ancient bracers', weight: 6),
  LootTableItem(name: 'Ancient d\'hide boots', weight: 6),
  LootTableItem(name: 'Ancient d\'hide shield', weight: 1),
  LootTableItem(name: 'Saradomin stole', weight: 6),
  LootTableItem(name: 'Saradomin crozier', weight: 6),
  LootTableItem(name: 'Guthix stole', weight: 6),
  LootTableItem(name: 'Guthix crozier', weight: 6),
  LootTableItem(name: 'Zamorak stole', weight: 6),
  LootTableItem(name: 'Zamorak crozier', weight: 6),
  LootTableItem(name: 'Zombie head', weight: 6),
  LootTableItem(name: 'Cyclops head', weight: 6),
  LootTableItem(name: 'Pirate\'s hat', weight: 6),
  LootTableItem(name: 'Red cavalier', weight: 6),
  LootTableItem(name: 'White cavalier', weight: 6),
  LootTableItem(name: 'Navy cavalier', weight: 6),
  LootTableItem(name: 'Tan cavalier', weight: 6),
  LootTableItem(name: 'Dark cavalier', weight: 6),
  LootTableItem(name: 'Black cavalier', weight: 6),
  LootTableItem(name: 'Pith helmet', weight: 6),
  LootTableItem(name: 'Explorer backpack', weight: 6),
  LootTableItem(name: 'Green dragon mask', weight: 6),
  LootTableItem(name: 'Blue dragon mask', weight: 6),
  LootTableItem(name: 'Red dragon mask', weight: 6),
  LootTableItem(name: 'Black dragon mask', weight: 6),
  LootTableItem(name: 'Nunchaku', weight: 6),
  LootTableItem(name: 'Dual sai', weight: 6),
  LootTableItem(name: 'Rune cane', weight: 6),
  LootTableItem(name: 'Thieving bag', weight: 6),
  LootTableItem(name: 'Dragon boots ornament kit', weight: 6),
  LootTableItem(name: 'Rune defender ornament kit', weight: 6),
  LootTableItem(name: 'Berserker necklace ornament kit', weight: 6),
  LootTableItem(name: 'Tzhaar-ket-om ornament kit', weight: 6),
  LootTableItem(name: 'Amulet of glory (t4)', weight: 6),
];

final List<LootTableItem> kHardRewardCommonTableItems = [
  LootTableItem(name: 'Rune full helm', weight: 10),
  LootTableItem(name: 'Rune platebody', weight: 10),
  LootTableItem(name: 'Rune platelegs', weight: 10),
  LootTableItem(name: 'Rune plateskirt', weight: 10),
  LootTableItem(name: 'Rune kiteshield', weight: 10),
  LootTableItem(name: 'Rune longsword', weight: 10),
  LootTableItem(name: 'Rune dagger', weight: 10),
  LootTableItem(name: 'Rune battleaxe', weight: 10),
  LootTableItem(name: 'Rune axe', weight: 10),
  LootTableItem(name: 'Rune pickaxe', weight: 10),
  LootTableItem(name: 'Black d\'hide body', weight: 10),
  LootTableItem(name: 'Black d\'hide chaps', weight: 10),
  LootTableItem(name: 'Magic shortbow', weight: 10),
  LootTableItem(name: 'Magic longbow', weight: 10),
  LootTableItem(name: 'Magic comp bow', weight: 1),
  LootTableItem.quantity(
      name: 'Nature rune', weight: 10, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Law rune', weight: 10, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Blood rune', weight: 10, quantityMin: 30, quantityMax: 50),
  LootTableItem.quantity(
      name: 'Lobster', weight: 10, quantityMin: 20, quantityMax: 30),
  LootTableItem.quantity(
      name: 'Shark', weight: 10, quantityMin: 20, quantityMax: 30),
];

final List<LootTableItem> kSharedRewardTableItems = [
  LootTableItem.quantity(
      name: 'Red firelighter', weight: 18, quantityMin: 3, quantityMax: 5),
  LootTableItem.quantity(
      name: 'Green firelighter', weight: 18, quantityMin: 3, quantityMax: 5),
  LootTableItem.quantity(
      name: 'Blue firelighter', weight: 18, quantityMin: 3, quantityMax: 5),
  LootTableItem.quantity(
      name: 'Purple firelighter', weight: 18, quantityMin: 3, quantityMax: 5),
  LootTableItem.quantity(
      name: 'White firelighter', weight: 18, quantityMin: 3, quantityMax: 5),
  LootTableItem.quantity(
      name: 'Coins', weight: 9, quantityMin: 10000, quantityMax: 15000),
  LootTableItem.quantity(
      name: 'Purple sweets', weight: 9, quantityMin: 8, quantityMax: 12),
  LootTableItem(name: 'Gnomish firelighter', weight: 9),
  LootTableItem.quantity(
      name: 'Charge dragonstone jewellery scroll',
      weight: 9,
      quantityMin: 5,
      quantityMax: 15),
  LootTableItem.quantity(
      name: 'Nardah teleport', weight: 9, quantityMin: 5, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Mos le\'harmless teleport',
      weight: 9,
      quantityMin: 5,
      quantityMax: 15),
  LootTableItem.quantity(
      name: 'Mort\'ton teleport', weight: 9, quantityMin: 5, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Feldip hills teleport',
      weight: 9,
      quantityMin: 5,
      quantityMax: 15),
  LootTableItem.quantity(
      name: 'Lunar isle teleport', weight: 9, quantityMin: 5, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Digsite teleport', weight: 9, quantityMin: 5, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Piscatoris teleport', weight: 9, quantityMin: 5, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Pest control teleport',
      weight: 9,
      quantityMin: 5,
      quantityMax: 15),
  LootTableItem.quantity(
      name: 'Tai bwo wannai teleport',
      weight: 9,
      quantityMin: 5,
      quantityMax: 15),
  LootTableItem.quantity(
      name: 'Lumberyard teleport', weight: 9, quantityMin: 5, quantityMax: 15),
  LootTableItem.quantity(
      name: 'Iorwerth camp teleport',
      weight: 9,
      quantityMin: 5,
      quantityMax: 15),
  LootTableItem(name: 'Master scroll book', weight: 3),
  LootTableItem(name: 'Saradomin page 1', weight: 3),
  LootTableItem(name: 'Saradomin page 2', weight: 3),
  LootTableItem(name: 'Saradomin page 3', weight: 3),
  LootTableItem(name: 'Saradomin page 4', weight: 3),
  LootTableItem(name: 'Zamorak page 1', weight: 3),
  LootTableItem(name: 'Zamorak page 2', weight: 3),
  LootTableItem(name: 'Zamorak page 3', weight: 3),
  LootTableItem(name: 'Zamorak page 4', weight: 3),
  LootTableItem(name: 'Guthix page 1', weight: 3),
  LootTableItem(name: 'Guthix page 2', weight: 3),
  LootTableItem(name: 'Guthix page 3', weight: 3),
  LootTableItem(name: 'Guthix page 4', weight: 3),
  LootTableItem(name: 'Bandos page 1', weight: 3),
  LootTableItem(name: 'Bandos page 2', weight: 3),
  LootTableItem(name: 'Bandos page 3', weight: 3),
  LootTableItem(name: 'Bandos page 4', weight: 3),
  LootTableItem(name: 'Armadyl page 1', weight: 3),
  LootTableItem(name: 'Armadyl page 2', weight: 3),
  LootTableItem(name: 'Armadyl page 3', weight: 3),
  LootTableItem(name: 'Armadyl page 4', weight: 3),
  LootTableItem(name: 'Ancient page 1', weight: 3),
  LootTableItem(name: 'Ancient page 2', weight: 3),
  LootTableItem(name: 'Ancient page 3', weight: 3),
  LootTableItem(name: 'Ancient page 4', weight: 3),
  LootTableItem(name: 'Holy blessing', weight: 1),
  LootTableItem(name: 'Unholy blessing', weight: 1),
  LootTableItem(name: 'Peaceful blessing', weight: 1),
  LootTableItem(name: 'War blessing', weight: 1),
  LootTableItem(name: 'Honourable blessing', weight: 1),
  LootTableItem(name: 'Ancient blessing', weight: 1)
];

List<LootTableItem> kTotalLootItems = [
  LootTableItem(name: 'Cabbage', weight: 1, price: 5000),
  LootTableItem(name: 'Black 2h sword', weight: 1, price: 2500),
  LootTableItem(name: 'Black axe', weight: 1, price: 2500),
  LootTableItem(name: 'Black battleaxe', weight: 1, price: 2500),
  LootTableItem(name: 'Black chainbody', weight: 1, price: 2500),
  LootTableItem(name: 'Black dagger', weight: 1, price: 2500),
  LootTableItem(name: 'Black full helm', weight: 1, price: 2500),
  LootTableItem(name: 'Black kiteshield', weight: 1, price: 2500),
  LootTableItem(name: 'Black longsword', weight: 1, price: 2500),
  LootTableItem(name: 'Black mace', weight: 1, price: 2500),
  LootTableItem(name: 'Black med helm', weight: 1, price: 2500),
  LootTableItem(name: 'Black pickaxe', weight: 1, price: 2500),
  LootTableItem(name: 'Black platebody', weight: 1, price: 2500),
  LootTableItem(name: 'Black plateskirt', weight: 1, price: 2500),
  LootTableItem(name: 'Black platelegs', weight: 1, price: 2500),
  LootTableItem(name: 'Black sq shield', weight: 1, price: 2500),
  LootTableItem(name: 'Black scimitar', weight: 1, price: 2500),
  LootTableItem(name: 'Black sword', weight: 1, price: 2500),
  LootTableItem(name: 'Black warhammer', weight: 1, price: 2500),
  LootTableItem(name: 'Shortbow', weight: 1, price: 1000),
  LootTableItem(name: 'Longbow', weight: 1, price: 1000),
  LootTableItem(name: 'Oak shortbow', weight: 1, price: 1000),
  LootTableItem(name: 'Oak longbow', weight: 1, price: 1000),
  LootTableItem(name: 'Iron pickaxe', weight: 1, price: 1000),
  LootTableItem(name: 'Staff of air', weight: 1, price: 1000),
  LootTableItem(name: 'Staff of water', weight: 1, price: 1000),
  LootTableItem(name: 'Staff of earth', weight: 1, price: 1000),
  LootTableItem(name: 'Staff of fire', weight: 1, price: 1000),
  LootTableItem(name: 'Steel full helm', weight: 1, price: 1000),
  LootTableItem(name: 'Steel platebody', weight: 1, price: 1000),
  LootTableItem(name: 'Steel platelegs', weight: 1, price: 1000),
  LootTableItem(name: 'Steel plateskirt', weight: 1, price: 1000),
  LootTableItem(name: 'Steel longsword', weight: 1, price: 1000),
  LootTableItem(name: 'Steel dagger', weight: 1, price: 1000),
  LootTableItem(name: 'Steel axe', weight: 1, price: 1000),
  LootTableItem(name: 'Steel battleaxe', weight: 1, price: 1000),
  LootTableItem(name: 'Leather cowl', weight: 1, price: 1000),
  LootTableItem(name: 'Leather body', weight: 1, price: 1000),
  LootTableItem(name: 'Leather chaps', weight: 1, price: 1000),
  LootTableItem(name: 'Leather vambraces', weight: 1, price: 1000),
  LootTableItem(name: 'Hardleather body', weight: 1, price: 1000),
  LootTableItem(name: 'Blue wizard hat', weight: 1, price: 1000),
  LootTableItem(name: 'Blue wizard robe', weight: 1, price: 1000),
  LootTableItem(name: 'Wizard hat', weight: 1, price: 1000),
  LootTableItem(name: 'Black robe', weight: 1, price: 1000),
  LootTableItem.quantity(
      name: 'Air rune',
      weight: 1,
      quantityMin: 15,
      quantityMax: 35,
      price: 100),
  LootTableItem.quantity(
      name: 'Mind rune',
      weight: 1,
      quantityMin: 15,
      quantityMax: 35,
      price: 100),
  LootTableItem.quantity(
      name: 'Water rune',
      weight: 1,
      quantityMin: 15,
      quantityMax: 35,
      price: 100),
  LootTableItem.quantity(
      name: 'Earth rune',
      weight: 1,
      quantityMin: 15,
      quantityMax: 35,
      price: 100),
  LootTableItem.quantity(
      name: 'Fire rune',
      weight: 1,
      quantityMin: 15,
      quantityMax: 35,
      price: 100),
  LootTableItem.quantity(
      name: 'Body rune',
      weight: 1,
      quantityMin: 15,
      quantityMax: 35,
      price: 100),
  LootTableItem.quantity(
      name: 'Chaos rune',
      weight: 1,
      quantityMin: 2,
      quantityMax: 7,
      price: 250),
  LootTableItem.quantity(
      name: 'Nature rune',
      weight: 1,
      quantityMin: 2,
      quantityMax: 9,
      price: 350),
  LootTableItem.quantity(
      name: 'Law rune', weight: 1, quantityMin: 2, quantityMax: 7, price: 250),
  LootTableItem.quantity(
      name: 'Death rune',
      weight: 1,
      quantityMin: 10,
      quantityMax: 20,
      price: 500),
  LootTableItem.quantity(
      name: 'Bronze arrow',
      weight: 1,
      quantityMin: 10,
      quantityMax: 25,
      price: 150),
  LootTableItem.quantity(
      name: 'Iron arrow',
      weight: 1,
      quantityMin: 7,
      quantityMax: 25,
      price: 150),
  LootTableItem.quantity(
      name: 'Shrimps', weight: 1, quantityMin: 5, quantityMax: 14, price: 200),
  LootTableItem.quantity(
      name: 'Sardine', weight: 1, quantityMin: 5, quantityMax: 17, price: 200),
  LootTableItem.quantity(
      name: 'Herring', weight: 1, quantityMin: 5, quantityMax: 9, price: 350),
  LootTableItem(name: 'Steel pickaxe', weight: 9, price: 3500),
  LootTableItem(name: 'Coif', weight: 9, price: 3500),
  LootTableItem(name: 'Studded body', weight: 9, price: 3500),
  LootTableItem(name: 'Studded chaps', weight: 9, price: 3500),
  LootTableItem(name: 'Willow shortbow', weight: 9, price: 3500),
  LootTableItem(name: 'Staff of air', weight: 9, price: 3500),
  LootTableItem(name: 'Willow longbow', weight: 9, price: 3500),
  LootTableItem(name: 'Amulet of magic', weight: 9, price: 3500),
  LootTableItem.quantity(
      name: 'Trout', weight: 9, quantityMin: 6, quantityMax: 10, price: 750),
  LootTableItem.quantity(
      name: 'Salmon', weight: 9, quantityMin: 6, quantityMax: 10, price: 750),
  LootTableItem.quantity(
      name: 'Lobster', weight: 1, quantityMin: 8, quantityMax: 12, price: 1000),
  LootTableItem.quantity(
      name: 'Swordfish',
      weight: 1,
      quantityMin: 8,
      quantityMax: 12,
      price: 1000),
  LootTableItem(name: 'Adamant full helm', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant platebody', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant platelegs', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant longsword', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant dagger', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant battleaxe', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant axe', weight: 10, price: 5000),
  LootTableItem(name: 'Adamant pickaxe', weight: 10, price: 5000),
  LootTableItem(name: 'Green d\'hide body', weight: 10, price: 5000),
  LootTableItem(name: 'Green d\'hide chaps', weight: 10, price: 5000),
  LootTableItem(name: 'Yew shortbow', weight: 10, price: 5000),
  LootTableItem(name: 'Fire battlestaff', weight: 10, price: 5000),
  LootTableItem(name: 'Yew longbow', weight: 10, price: 5000),
  LootTableItem(name: 'Amulet of power', weight: 10, price: 5000),
  LootTableItem.quantity(
      name: 'Shark', weight: 10, quantityMin: 20, quantityMax: 30, price: 2000),
  LootTableItem.quantity(
      name: 'Blood rune',
      weight: 10,
      quantityMin: 30,
      quantityMax: 50,
      price: 750),
  LootTableItem(name: 'Rune full helm', weight: 10, price: 7500),
  LootTableItem(name: 'Rune platebody', weight: 10, price: 7500),
  LootTableItem(name: 'Rune platelegs', weight: 10, price: 7500),
  LootTableItem(name: 'Rune plateskirt', weight: 10, price: 7500),
  LootTableItem(name: 'Rune kiteshield', weight: 10, price: 7500),
  LootTableItem(name: 'Rune longsword', weight: 10, price: 7500),
  LootTableItem(name: 'Rune dagger', weight: 10, price: 7500),
  LootTableItem(name: 'Rune battleaxe', weight: 10, price: 7500),
  LootTableItem(name: 'Rune axe', weight: 10, price: 7500),
  LootTableItem(name: 'Rune pickaxe', weight: 10, price: 7500),
  LootTableItem(name: 'Black d\'hide body', weight: 10, price: 7500),
  LootTableItem(name: 'Black d\'hide chaps', weight: 10, price: 7500),
  LootTableItem(name: 'Magic shortbow', weight: 10, price: 7500),
  LootTableItem(name: 'Magic longbow', weight: 10, price: 7500),
  LootTableItem.quantity(
      name: 'Super energy(4)',
      weight: 13,
      quantityMin: 15,
      quantityMax: 15,
      price: 15000),
  LootTableItem.quantity(
      name: 'Super restore(4)',
      weight: 13,
      quantityMin: 15,
      quantityMax: 15,
      price: 15000),
  LootTableItem.quantity(
      name: 'Antifire potion(4)',
      weight: 13,
      quantityMin: 15,
      quantityMax: 15,
      price: 15000),
  LootTableItem.quantity(
      name: 'Super combat potion(4)',
      weight: 13,
      quantityMin: 15,
      quantityMax: 15,
      price: 15000),
];
